<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email yang Anda masukkan tidak terhubung ke akun. Cari akun Anda dan login</name>
   <tag></tag>
   <elementGuidId>f365b26b-f685-40b5-a678-e5143e1b5f92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginform']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loginform</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ee1046f6-14e4-4ea5-a5b0-9fbc79e9bd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginform</value>
      <webElementGuid>dc6400ee-6d38-4251-b8f4-7a03703d4586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email yang Anda masukkan tidak terhubung ke akun. Cari akun Anda dan login.MasukLupa Kata Sandi?</value>
      <webElementGuid>7a6a4ad5-2d7f-498b-b069-4f57efc3c110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginform&quot;)</value>
      <webElementGuid>5b5a2090-5d58-4dde-a1a0-535531643725</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='loginform']</value>
      <webElementGuid>6f35ceae-c824-441c-ab90-a23db13fafdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div</value>
      <webElementGuid>c9019b70-0f7e-4ce4-9c28-3330978b8047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login ke Facebook'])[1]/following::div[2]</value>
      <webElementGuid>2086a92c-8b90-48df-b98f-5d7e72acda9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>db7b0b8c-960b-43f2-9c0d-f5ac8c138cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'loginform' and (text() = 'Email yang Anda masukkan tidak terhubung ke akun. Cari akun Anda dan login.MasukLupa Kata Sandi?' or . = 'Email yang Anda masukkan tidak terhubung ke akun. Cari akun Anda dan login.MasukLupa Kata Sandi?')]</value>
      <webElementGuid>345af666-24fe-438e-bf1d-1492eb43a270</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
